version: '3.8'

services:
  mysql:
    extends:
      file: docker/compose/mysql.yml
      service: mysql

  backend:
    extends:
      file: docker/compose/server.yml
      service: backend

  frontend:
    extends: 
      file: docker/compose/client.yml
      service: frontend

volumes:
  mysql_data: