version: '3.8'

services:
  mysql:
    extends:
      file: docker/compose/mysql.yml
      service: mysql

  server:
    extends:
      file: docker/compose/server.yml
      service: server

  client:
    extends: 
      file: docker/compose/client.yml
      service: client

volumes:
  mysql_data: