INSERT INTO courses (course_title, course_code, course_description) VALUES
("Introduction to Computer Programming", "CS 102", "A fundamental guide on how to write computer programs with Java"),
("Data Structures and Algorithms", "CS 201", "An in-depth study of data structures and their associated algorithms"),
("Operating Systems", "CS 301", "Essentials of operating systems, focusing on process management and memory management"),
("Database Management Systems", "CS 401", "Key concepts in relational databases and SQL"),
("Computer Networks", "CS 501", "Basics of networking, including protocols, architectures, and the internet"),
("Advanced Operating Systems", "CS 601", "A formal guide on distributed operating systems and parallel processing"),
("Software Design and Architecture", "CS 701", "Principles of software architecture and design patterns"),
("Theory of Computation", "CS 801", "An introduction to the theoretical foundations of computer science"),
("Machine Learning Fundamentals", "CS 901", "Mastering the basics of machine learning algorithms and models"),
("Cloud Computing", "CS 1001", "Key concepts in cloud computing, including deployment models and services"),
("Artificial Intelligence", "CS 1999", "An overview of AI, including machine learning, neural networks, and robotics"),
("Artificial Intelligence", "CS 1002", "A deep dive into artificial intelligence and neural networks"),
("Introduction to Cybersecurity", "CS 1003", "An overview of cybersecurity principles and practices"),
("Software Testing and Quality Assurance", "CS 1004", "Best practices in software testing and ensuring code quality"),
("Introduction to DevOps", "CS 1005", "An introduction to DevOps culture and practices"),
("Big Data Analytics", "CS 1006", "Fundamentals of big data processing and analysis"),
("Natural Language Processing", "CS 1007", "A guide to processing and analyzing human language data"),
("Computer Vision", "CS 1008", "Techniques and algorithms for image processing and analysis"),
("Blockchain Technology", "CS 1009", "An introduction to blockchain and distributed ledger technologies"),
("Quantum Computing", "CS 1010", "Basics of quantum computing and its applications"),
("Advanced Data Structures", "CS 1011", "Advanced topics in data structures and their efficient implementation");
