version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: asc-cms-api-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coursedb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql