name: Build Project

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: test_db
      DB_USER: root
      DB_PASSWORD: root

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Cache Gradle Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Print Working Directory
        run: pwd
      
      - name: Start MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE;" -u$DB_USER -p$DB_PASSWORD

      - name: Build with Gradle
        run: ./gradlew build --no-daemon
        working-directory: ./asc-courses-api

      - name: Run Unit Tests
        run: ./gradlew test --no-daemon
        working-directory: ./asc-courses-api

      - name: Check Code Quality
        run: ./gradlew check --no-daemon
        working-directory: ./asc-courses-api

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./asc-courses-api/build/reports/tests/test/

      - name: Upload Test Coverage Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage-report
          path: ./asc-courses-api/build/reports/jacoco/test/html/
